# Generated by Django 2.0.5 on 2018-05-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
