# Generated by Django 2.0.5 on 2018-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_v1', '0002_remove_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('url', models.URLField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
