# Generated by Django 2.0.5 on 2018-05-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_v1', '0003_similarity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Similarity',
            new_name='SimilarityRes',
        ),
    ]
