# Generated by Django 2.0.5 on 2018-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_v1', '0005_auto_20180530_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_input',
            field=models.TextField(default='bal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='corpus',
            field=models.CharField(choices=[('corpus_1', '/Users/Erik/Documents/Utdanning'), ('corpus_2', '/Users/Erik/Documents/Jobb'), ('corpus_3', '/Users/Erik/Dropbox/TekniskBibliotek/Vannkraft')], default='/Users/Erik/Documents/Python/NLP/Extraction/Corpus/corpus.mm', max_length=200),
        ),
    ]
