# Generated by Django 2.0.5 on 2018-06-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_v1', '0006_auto_20180605_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='corpus',
            new_name='directory',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_input',
            field=models.TextField(blank=True),
        ),
    ]
