# Generated by Django 2.0.5 on 2018-06-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_v1', '0008_auto_20180613_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarityres',
            name='sim_score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
