# Generated by Django 2.1 on 2018-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_v1', '0009_auto_20180615_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='directory',
            field=models.CharField(choices=[('corpus_1', 'C:\\Users\\ERDIG\\Documents')], default='/Users/Erik/Documents/Python/NLP/Extraction/Corpus/corpus.mm', max_length=200),
        ),
    ]
