# Generated by Django 2.0.5 on 2018-06-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0002_auto_20180614_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryres',
            name='url',
        ),
        migrations.AddField(
            model_name='summaryres',
            name='doc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='file',
            field=models.FileField(upload_to='sum_v1/upload'),
        ),
    ]
