# Generated by Django 2.0.5 on 2018-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0004_auto_20180614_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
