# Generated by Django 2.0.5 on 2018-06-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0005_auto_20180614_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='title',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='uploaded_at',
        ),
    ]
