# Generated by Django 2.0.5 on 2018-06-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0010_file_upload_word_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField(choices=[('50', 50), ('200', 200), ('500', 500)], default=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='word_count',
        ),
    ]
