# Generated by Django 2.0.5 on 2018-06-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0011_auto_20180615_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='word_count',
            field=models.CharField(max_length=500),
        ),
    ]
