# Generated by Django 2.0.5 on 2018-06-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0012_auto_20180615_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordCount',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='word_count',
            field=models.IntegerField(choices=[('50', 50), ('200', 200), ('500', 500)], default=200),
        ),
    ]
