# Generated by Django 2.0.5 on 2018-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0013_auto_20180615_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='word_count',
            field=models.IntegerField(blank=True, default=200),
        ),
    ]
