# Generated by Django 2.0.5 on 2018-06-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0015_auto_20180615_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField(choices=[('50', 50), ('200', 200), ('500', 500)], default=200)),
            ],
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='word_count',
            field=models.IntegerField(blank=True, default=200),
        ),
    ]
