# Generated by Django 2.0.5 on 2018-06-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0016_auto_20180615_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='word_count',
        ),
    ]
