# Generated by Django 2.0.5 on 2018-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0017_remove_file_upload_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='word_count',
            field=models.IntegerField(blank=True, default=200),
        ),
    ]
