# Generated by Django 2.0.5 on 2018-06-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0018_file_upload_word_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordCount',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='word_count',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='sum_words',
            field=models.IntegerField(blank=True, choices=[('50', 50), ('200', 200), ('500', 500)], default=200),
        ),
    ]
