# Generated by Django 2.1 on 2018-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_v1', '0019_auto_20180617_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='sum_words',
            field=models.IntegerField(blank=True, default=200),
        ),
    ]
